# holder for app
id: default_system
title: Default System app
type: project
version: 0.1.0
icon: app.png
introduction:
  format: markdown
  template: |
    Use this app to achieve ISM compliance.
catalog:
  category: Draft
  description:
    long: >
      Edit this Markdown file to provide a long description of your compliance app.
      The contents of this file will be displayed in the GovReady-Q Compliance Apps
      Catalog.
    short: A system for ISM compliance
  source_url: ~
  status: stub
  title: Default ISM System
  vendor: GovReady
  vendor_url: ~
  version: 0.1.0
questions:
- id: register
  title: System Registration
  type: module
  module-id: register
- id: assess
  title: Assess System
  type: module
  module-id: assess