# holder for app
id: default_system
title: Default System app
type: project
version: 0.1.0
icon: app.png
introduction:
  format: markdown
  template: |
    Use this app to achieve ISM compliance.
catalog:
  category: Draft
  description:
    long: >
      A system to ensure that you can meet ISM compliance with minimum fuss
    short: A system for ISM compliance
  source_url: ~
  status: stub
  title: Default ISM System
  vendor: GovReady
  vendor_url: ~
  version: 0.1.0
questions:
  - id: register
    title: System Registration
    type: module
    module-id: register
  - id: assess
    title: Assess System
    type: module
    module-id: assess
  - id: authorise
    title: authorise System
    type: module
    module-id: authorise